coverage:
  status:
    project:
      default: off
      unit-tests:
        target: 30%
        flags: unit
      integration-tests:
        target: 60%
        flags: integration

ignore:
- "^.*_gen.go$"
- "^.*_string.go$"
- "generate"
- "cmd"
